---
- name: Create application directory
  file:
    path: /opt/sample-app
    state: directory

- name: Copy JAR file
  copy:
    src: app/target/sample-app-1.0.0.jar
    dest: /opt/sample-app/sample-app.jar
    mode: '0755'

- name: Install systemd service
  template:
    src: app.service.j2
    dest: /etc/systemd/system/sample-app.service

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Start application
  systemd:
    name: sample-app
    state: restarted
    enabled: yes
